import sys

print("=" * 70)
print("RENDER DEPLOYMENT PLAN")
print("=" * 70)

print("\n[STEP 1] Push code to GitHub")
print("  git add .")
print("  git commit -m 'Prepare for Render deployment'")
print("  git push origin main")

print("\n[STEP 2] Create Render Web Service")
print("  1. Go to https://render.com")
print("  2. Click 'New +' -> 'Web Service'")
print("  3. Connect your GitHub repository")
print("  4. Select the yt2medium repository")

print("\n[STEP 3] Configure Service")
print("  Name: yt2medium")
print("  Environment: Python 3")
print("  Build Command: ./build.sh")
print("  Start Command: gunicorn -c gunicorn_config.py app:app")
print("  Plan: Free (or Starter)")

print("\n[STEP 4] Add Environment Variables")
print("  Required:")
print("    - OPENAI_API_KEY")
print("    - OPENROUTER_API_KEY")
print("    - SECRET_KEY")
print("    - FLASK_ENV=production")
print("  ")
print("  Optional (if using):")
print("    - ANTHROPIC_API_KEY")
print("    - HUGGINGFACE_TOKEN")
print("    - PROJECT_ID")
print("    - LOCATION")
print("    - SUPABASE_URL")
print("    - SUPABASE_KEY")

print("\n[STEP 5] Deploy")
print("  Click 'Create Web Service'")
print("  Wait for build to complete (5-10 minutes)")

print("\n[STEP 6] Access Your App")
print("  URL will be: https://yt2medium.onrender.com")
print("  (or your custom subdomain)")

print("\n" + "=" * 70)
print("FILES CREATED FOR DEPLOYMENT")
print("=" * 70)
print("  - build.sh (build script)")
print("  - render.yaml (service config)")
print("  - gunicorn_config.py (production server config)")
print("  - requirements.txt (already exists)")

print("\n" + "=" * 70)
print("IMPORTANT NOTES")
print("=" * 70)
print("  1. Free tier sleeps after 15min inactivity")
print("  2. First request after sleep takes 30-60 seconds")
print("  3. temp_posts/ directory is ephemeral on free tier")
print("  4. For persistent storage, use Supabase")
print("  5. Set FLASK_ENV=production for better performance")

print("\n" + "=" * 70)
print("READY TO DEPLOY!")
print("=" * 70)
